config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/home'
  root to: 'dashboard#home'

  namespace :api do
    resources :events
    resources :announcements
    resources :tasks
    get '/settings/trash', to: 'settings#todays_trash'
    get '/settings/exchange', to: 'settings#exchange'
  end

  resources :events
  resources :announcements
  resources :tasks
  resources :settings
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def home
    @announcements = Announcement.all

    two_days_events = Event.get_two_days_events(Date.current)
    @todays_events = two_days_events["current"]
    @tomorrows_events = two_days_events["next"]

    two_days_tasks = Task.get_two_days_tasks(Date.current)
    @todays_start_tasks = two_days_tasks["current_start"]
    @todays_deadline_tasks = two_days_tasks["current_deadline"]
    @tomorrows_start_tasks = two_days_tasks["next_start"]
    @tomorrows_deadline_tasks = two_days_tasks["next_deadline"]
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/home.html.erb
<% provide :title, "Dashboard" %>
<% provide :dashb_is_active, "active" %>

<div class="row">
  <div class="col m6 s12 l6 xl6 announcements">
    <%= render 'announcements/card' %>
  </div>

  <div class="col m6 s12 l6 xl6 events">
    <%= render 'events/card' %>
  </div>

  <div class="col m6 s12 l6 xl6 tasks">
    <%= render 'tasks/card' %>
  </div>

  <div class="fixed-action-btn click-to-toggle">
    <a class="btn-floating btn-large red">
      <i class="material-icons">add</i>
    </a>

    <ul>
      <li>
        <%= link_to new_task_path, remote: true, class: "btn-floating red" do %>
          <i class="material-icons">assignment</i>
        <% end %>
      </li>
      <li>
        <%= link_to new_event_path, remote: true, class: "btn-floating orange" do %>
          <i class="material-icons">event</i>
        <% end %>
      </li>
      <li>
        <%= link_to new_announcement_path, remote: true, class: "btn-floating yellow" do %>
          <i class="material-icons">question_answer</i>
        <% end %>
      </li>
    </ul>
  </div>
</div>