config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/home'
  root to: 'dashboard#home'

  namespace :api do
    resources :events
    resources :announcements
    resources :tasks
    get '/settings/trash', to: 'settings#todays_trash'
    get '/settings/exchange', to: 'settings#exchange'
  end

  resources :events
  resources :announcements
  resources :tasks
  resources :settings
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  validates :timing, inclusion: { in: [true, false] }
  validates :mode, presence: true

  enum mode: { weather: 0, trash: 1, exchange: 2 }

  def self.jp_translated_modes
    { 'weather' => '天気', 'trash' => 'ゴミ出し', 'exchange' => '為替' }
  end

  def self.jp_translated_timing
    { true => '家を出るとき', false => '家に帰ったとき' }
  end

  def self.mode_icons_and_colors
    {
      'weather' => %w[wb_sunny orange],
      'trash' => %w[whatshot red],
      'exchange' => %w[timeline yellow]
    }
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:show, :edit, :update, :destroy]
  # render_form at app_controller
  around_action :render_form, only: [:new, :edit]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all
    @announcement = Announcement.new
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to dashboard_home_path }
        format.json { render 'announcement', status: :created, announcement: @announcement }
      else
        format.html { render :new }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to dashboard_home_path, notice: 'Announcement was successfully updated.' }
      else
        format.html { render html: 'shit', status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_home_path, notice: 'Announcement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.require(:announcement).permit(:date, :timing, :mode)
    end
end

app/controllers/api/announcements_controller.rb
class Api::AnnouncementsController < ApplicationController
  before_action :set_announcement, only: [:update]
  protect_from_forgery :except => [:create, :update, :destroy]

  # GET /announcements
  # GET /announcements.json
  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html { render html: '200' }
      format.json { render 'announcements/index', announcements: @announcements, status: :ok }
    end
  end

  # POST /announcements
  # POST /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { render html: '200' }
        format.json { render 'announcements/announcement', status: :created, announcement: @announcement }
      else
        format.html { render html: '500', status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1
  # PATCH/PUT /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { render html: '200', status: :ok }
        format.json { render 'announcements/announcement', status: :ok, announcement: @announcement }
      else
        format.html { render html: '500', status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.json
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy
    respond_to do |format|
      format.html { render html: '200', status: :ok }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def announcement_params
      params.permit(:date, :timing, :mode)
    end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_card.html.erb
<div class="card hoverable">
  <div class="progress">
    <div class="indeterminate"></div>
  </div>

  <div class="card-content">
    <span class="card-title activator">お知らせ</span>
  </div>

  <div class="card-stacked">
    <div class="card-content">
      <% unless @announcements.nil? %>
        <ul class="collection">
          <% @announcements.each do |anc| %>
            <%= render 'announcements/column', announce: anc %>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/announcements/_column.html.erb
<% icon_set = Announcement.mode_icons_and_colors[announce.mode] %>
<li class="collection-item avatar">
  <i class="material-icons circle <%= icon_set[1] %>"><%= icon_set[0] %></i>
  <span class="title"><%= Announcement.jp_translated_modes[announce.mode] %></span>
  <p>
    <%= Announcement.jp_translated_timing[announce.timing] %>
  </p>

  <%= link_to edit_announcement_path(announce), remote: true, class: 'btn-floating secondary-content' do %>
    <i class="material-icons">edit</i>
  <% end %>
</li>

app/views/announcements/_form.html.erb
<%= form_with(model: @announcement, local: true) do |form| %>
  <% if form.object.new_record? %>
    <% provide :form_title, "New" %>
    <% selected = "normal" %>
    <% field_activated = "" %>
  <% else %>
    <% provide :form_title, "Edit" %>
    <% slctd_mode = @announcement.mode %>
    <% field_activated = "active" %>
  <% end %>

  <div class="modal-content">
    <h3><%= yield :form_title %></h3>

    <div class="row">
      <div class="col s12 m3 l3 xl3 input-field">
        <%= form.select :timing, Announcement.jp_translated_timing.invert, required: true %>
        <%= form.label :timing, "タイミング" %>
      </div>
      <div class="col s12 m3 l3 xl3 input-field">
        <%= form.select :mode, Announcement.jp_translated_modes.invert, required: true %>
        <%= form.label :mode, "内容" %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <a class="modal-action modal-close btn-flat left">Cancel</a>

    <% unless form.object.new_record? %>
      <%= link_to announcement, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' }, class: 'btn waves-effect waves-light red left' do %>
        DELETE
      <% end %>
    <% end %>

    <button id="submit" class="btn waves-effect waves-light right" type="submit" name="action">
      Save
    </button>
  </div>
<% end %>

app/views/announcements/index.html.erb
<% provide :title, "All Announcement" %>
<% provide :announcements_is_active, "active" %>

<div class="row">
  <div class="col s12">
    <div class="card">
      <div class="card-content">
        <span class="card-title activator">お知らせ</span>
      </div>

      <div class="card-stacked">
        <div class="card-content">
          <% unless @announcements.nil? %>
            <ul class="collection">
              <% @announcements.each do |anc| %>
                <%= render 'announcements/column', announce: anc %>
              <% end %>
            </ul>
          <% end %>
        </div>

        <div class="card-action">
          <%= link_to new_announcement_path, remote: true, class: 'btn waves-effect waves-light' do %>
            NEW
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>