config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/home'
  root to: 'dashboard#home'

  namespace :api do
    resources :events
    resources :announcements
    resources :tasks
    get '/settings/trash', to: 'settings#todays_trash'
    get '/settings/exchange', to: 'settings#exchange'
  end

  resources :events
  resources :announcements
  resources :tasks
  resources :settings
end

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper container">
      <span class="brand-logo"><a href="/">GenCon</a> <span class="hide-on-small-only">- <%= yield :title %></span> </span>
      <a href="" class="button-collapse" data-activates="sidenav" >
        <i class="material-icons">menu</i>
      </a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <%= render 'layouts/navigations' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigations.html.erb
<li class="<%= yield :dashb_is_active %>"><%= link_to "ダッシュボード", dashboard_home_path %></li>
<li class="<%= yield :announcements_is_active %>"><%= link_to "お知らせ", announcements_path %></li>
<li class="<%= yield :events_is_active %>"><%= link_to "イベント", events_path %></li>
<li class="<%= yield :tasks_is_active %>"><%= link_to "タスク", tasks_path %></li>
<li class="<%= yield :settings_is_active %>"><%= link_to "設定", settings_path %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Gencon - <%= yield :title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <!-- for side navbar, hide on large resolution -->
    <ul id="sidenav" class="side-nav">
      <li class="logo center-align">
        <%= image_tag 'gencon-logo-square', class: 'logo'%>
      </li>
      <%= render 'layouts/navigations' %>
    </ul>
  </div>
    <div class="container main">
      <%= yield %>
      <div id="form" class="load_point modal bottom-sheet btmsht-fullsized"></div>
    </div>

    <!-- <div id="loader-bg">
      <div id="loading-effect">
        <div class="preloader-wrapper big active">
          <div class="spinner-layer spinner-blue-only">
            <div class="circle-clipper left">
              <div class="circle"></div>
            </div><div class="gap-patch">
              <div class="circle"></div>
            </div><div class="circle-clipper right">
              <div class="circle"></div>
            </div>
          </div>
        </div>
      </div>
    </div> -->
  </body>
</html>